### ISSUE TITLE
Broken link in https://www.thinkful.com/projects/node-endpoint-testing/

### ISSUE THREAD

**Issue by danfriedman** [Thinkful-Ed/thinkful-projects#42]
"this introduction to Behaviour-Driven Development" -> links to a broken URL (https://www.thinkful.com/projects/node-endpoint-testing/Introduction%20to%20Behavior-Driven%20Development%20with%20JS%20-%20Chapter%201)

**Comment by oampo** [comment]
This is a link to one of the books which isn't in the app yet.  Not sure what to do with these at the moment.

**Comment by danfriedman** [comment]
Ah – that works then. Coming soon...

**Comment by danfriedman** [comment]
@oampo there are another 7 books live. is this live yet? https://docs.google.com/spreadsheets/d/1Zgx5ObMFN3Xl8Q3ZozLvfz6SN-yPXjvnmt4FGEnn2ts/edit#gid=0

**Comment by oampo** [comment]
Yep, it is.  Will fix in the app.

**Comment by danfriedman** [comment]
Great. Will close here in the meantime
